version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - github-actions
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      npm-tooling:
        patterns:
          - "*"
    labels:
      - dependencies
      - npm
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      python-qa:
        patterns:
          - "*"
    labels:
      - dependencies
      - python
